import type { LeagueConfig } from "./types";

export const LEAGUE_LOGOS: Record<number, string> = {
  128: "https://media.api-sports.io/football/leagues/128.png",
  1032: "https://media.api-sports.io/football/leagues/1032.png",
  130: "https://media.api-sports.io/football/leagues/130.png",
  265: "https://media.api-sports.io/football/leagues/265.png",
  267: "https://media.api-sports.io/football/leagues/267.png",
  239: "https://media.api-sports.io/football/leagues/239.png",
  71: "https://media.api-sports.io/football/leagues/71.png",
  73: "https://media.api-sports.io/football/leagues/73.png",
  281: "https://media.api-sports.io/football/leagues/281.png",
  503: "https://media.api-sports.io/football/leagues/503.png",
  501: "https://media.api-sports.io/football/leagues/501.png",
  268: "https://media.api-sports.io/football/leagues/268.png",
  930: "https://media.api-sports.io/football/leagues/930.png",
  13: "https://media.api-sports.io/football/leagues/13.png",
  11: "https://media.api-sports.io/football/leagues/11.png",
  2: "https://media.api-sports.io/football/leagues/2.png",
  3: "https://media.api-sports.io/football/leagues/3.png",
  140: "https://media.api-sports.io/football/leagues/140.png",
  39: "https://media.api-sports.io/football/leagues/39.png",
  78: "https://media.api-sports.io/football/leagues/78.png",
  80: "https://media.api-sports.io/football/leagues/80.png",
  135: "https://r2.thesportsdb.com/images/media/league/badge/67q3q21679951383.png",
  137: "https://media.api-sports.io/football/leagues/137.png",
  332: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Major_League_Soccer_logo.svg/250px-Major_League_Soccer_logo.svg.png",
  235: "https://media.api-sports.io/football/leagues/235.png",
  5: "https://media.api-sports.io/football/leagues/5.png",
  431: "https://media.api-sports.io/football/leagues/431.png",
};

export function getLeagueLogo(leagueId: number): string {
  return LEAGUE_LOGOS[leagueId] || "";
}

export function getLeagueIdByName(name: string): number {
  const league = SUPPORTED_LEAGUES.find(
    (l) => l.name.toLowerCase() === name.toLowerCase()
  );
  return league?.id ?? 0;
}

/**
 * Agenda acotada: primeras + copas de AR/CL/BR/PE/PY/UY,
 * Libertadores/Sudamericana, y top Europa (Champions, Europa, La Liga, Premier).
 */
export const SUPPORTED_LEAGUES: LeagueConfig[] = [
  // Argentina
  { id: 128, name: "Liga Profesional", country: "Argentina", countryFlag: "🇦🇷", slug: "liga-argentina", season: 2026 },
  { id: 130, name: "Copa Argentina", country: "Argentina", countryFlag: "🇦🇷", slug: "copa-argentina", season: 2026 },
  // Brasil
  { id: 71, name: "Brasileirão Serie A", country: "Brasil", countryFlag: "🇧🇷", slug: "brasileirao", season: 2026 },
  { id: 73, name: "Copa do Brasil", country: "Brasil", countryFlag: "🇧🇷", slug: "copa-do-brasil", season: 2026 },
  // Uruguay
  { id: 268, name: "Liga AUF Uruguaya", country: "Uruguay", countryFlag: "🇺🇾", slug: "liga-auf-uruguaya", season: 2026 },
  // Chile
  { id: 265, name: "Liga de Primera", country: "Chile", countryFlag: "🇨🇱", slug: "liga-de-primera", season: 2026 },
  { id: 267, name: "Copa Chile", country: "Chile", countryFlag: "🇨🇱", slug: "copa-chile", season: 2026 },
  // Colombia
  { id: 239, name: "Liga BetPlay", country: "Colombia", countryFlag: "🇨🇴", slug: "liga-betplay", season: 2026 },
  // CONMEBOL
  { id: 13, name: "Copa Libertadores", country: "Internacional", countryFlag: "🌎", slug: "copa-libertadores", season: 2026 },
  { id: 11, name: "Copa Sudamericana", country: "Internacional", countryFlag: "🌎", slug: "copa-sudamericana", season: 2026 },
  // UEFA
  { id: 2, name: "Champions League", country: "Internacional", countryFlag: "🌎", slug: "champions-league", season: 2026 },
  { id: 3, name: "Europa League", country: "Internacional", countryFlag: "🌎", slug: "europa-league", season: 2026 },
  { id: 140, name: "La Liga", country: "España", countryFlag: "🇪🇸", slug: "la-liga", season: 2026 },
  { id: 39, name: "Premier League", country: "Inglaterra", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", slug: "premier-league", season: 2026 },
  { id: 78, name: "Bundesliga", country: "Alemania", countryFlag: "🇩🇪", slug: "bundesliga", season: 2026 },
  // Italia
  { id: 135, name: "Serie A", country: "Italia", countryFlag: "🇮🇹", slug: "serie-a-italia", season: 2026 },
  // USA / CONCACAF
  { id: 332, name: "MLS", country: "Estados Unidos", countryFlag: "🇺🇸", slug: "mls", season: 2026 },
  { id: 5, name: "CONCACAF Champions Cup", country: "Internacional", countryFlag: "🌎", slug: "concacaf-champions-cup", season: 2026 },
];

export const API_FOOTBALL_BASE = "https://v3.football.api-sports.io";

export const LIVE_STATUSES = ["1H", "HT", "2H", "ET", "BT", "P", "INT", "LIVE"];
export const FINISHED_STATUSES = ["FT", "AET", "PEN", "AWD", "WO"];
export const UPCOMING_STATUSES = ["NS", "TBD"];
export const CANCELLED_STATUSES = ["SUSP", "PST", "CANC", "ABD"];

export const DEMO_STREAMS: { id: string; name: string; url: string }[] = [
  { id: "ch1", name: "Canal 1", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  { id: "ch2", name: "Canal 2", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
  { id: "ch3", name: "Canal 3", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
];

export const CHANNEL_SETS: Record<string, { id: string; name: string; url: string }[]> = {
  argentina: [
    { id: "tyc", name: "TyC Sports", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
    { id: "espn", name: "ESPN", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "dsports", name: "DSports", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
    { id: "tnt", name: "TNT Sports", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  brasil: [
    { id: "sporv", name: "SporTV", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "globo", name: "Globo", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
    { id: "premier", name: "Premiere", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  chile: [
    { id: "espn_cl", name: "ESPN", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "tnt_cl", name: "TNT Sports", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
    { id: "cdf", name: "CDF", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
  ],
  colombia: [
    { id: "win_co", name: "Win Sports", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "espn_co", name: "ESPN", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
    { id: "dsports_co", name: "DSports", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
  ],
  peru: [
    { id: "movistar_pe", name: "Movistar Deportes", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "latina", name: "Latina", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  paraguay: [
    { id: "tigo_py", name: "Tigo Sports", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "espn_py", name: "ESPN", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  uruguay: [
    { id: "dsports_uy", name: "DSports", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "espn_uy", name: "ESPN", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  españa: [
    { id: "movistar", name: "Movistar Plus+", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "dazn_es", name: "DAZN", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
    { id: "espn_es", name: "ESPN", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  inglaterra: [
    { id: "sky_sports", name: "Sky Sports", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "tnt_sports", name: "TNT Sports", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
    { id: "prime", name: "Prime Video", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  internacional: [
    { id: "espn2", name: "ESPN 2", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "fox2", name: "Fox Sports 2", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
    { id: "dazn", name: "DAZN", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
  ],
  default: [
    { id: "ch1", name: "Canal 1", url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" },
    { id: "ch2", name: "Canal 2", url: "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8" },
    { id: "ch3", name: "Canal 3", url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8" },
  ],
};

export function getChannelsForCountry(country: string): { id: string; name: string; url: string }[] {
  const key = country.toLowerCase();
  if (key.includes("argentina")) return CHANNEL_SETS.argentina;
  if (key.includes("brasil") || key.includes("brazil")) return CHANNEL_SETS.brasil;
  if (key.includes("chile")) return CHANNEL_SETS.chile;
  if (key.includes("colombia") || key.includes("colombian")) return CHANNEL_SETS.colombia;
  if (key.includes("perú") || key.includes("peru")) return CHANNEL_SETS.peru;
  if (key.includes("paraguay")) return CHANNEL_SETS.paraguay;
  if (key.includes("uruguay")) return CHANNEL_SETS.uruguay;
  if (key.includes("españa") || key.includes("spain")) return CHANNEL_SETS.españa;
  if (key.includes("inglaterra") || key.includes("england")) return CHANNEL_SETS.inglaterra;
  if (key.includes("estados unidos") || key.includes("united states") || key.includes("usa")) return CHANNEL_SETS.internacional;
  if (key.includes("mexico") || key.includes("méxico")) return CHANNEL_SETS.internacional;
  if (key.includes("italia") || key.includes("italy")) return CHANNEL_SETS.internacional;
  if (key.includes("internacional") || key.includes("europa")) return CHANNEL_SETS.internacional;
  return CHANNEL_SETS.default;
}

export const BROADCAST_CHANNELS: Record<number, string[]> = {
  128: ["TyC Sports", "ESPN", "TNT Sports", "DSports"],
  1032: ["TyC Sports Play", "ESPN"],
  130: ["TyC Sports", "ESPN"],
  265: ["ESPN", "TNT Sports", "CDF"],
  267: ["ESPN", "TNT Sports"],
  239: ["Win Sports", "ESPN", "DSports"],
  71: ["SporTV", "Premiere", "Globo"],
  73: ["SporTV", "Globo", "Premiere"],
  281: ["Latina Televisión", "Movistar Deportes"],
  503: ["Latina Televisión", "Movistar Deportes"],
  501: ["Tigo Sports", "ESPN"],
  268: ["DSports", "ESPN"],
  930: ["DSports", "ESPN"],
  13: ["ESPN", "Fox Sports", "DSports", "ESPN Premium"],
  11: ["ESPN", "Fox Sports", "DSports"],
  2: ["HBO Max", "ESPN", "Fox Sports", "DSports", "Movistar Plus+"],
  3: ["HBO Max", "ESPN", "Fox Sports", "DSports"],
  140: ["Movistar Plus+", "DAZN", "ESPN"],
  39: ["Sky Sports", "TNT Sports", "Prime Video"],
  135: ["ESPN", "DAZN", "Sky Sport"],
  137: ["ESPN", "DAZN", "Sky Sport"],
  332: ["Apple TV", "Fox Sports", "ESPN"],
  235: ["Fox Sports", "ESPN", "TUDN", "ViX"],
  5: ["Fox Sports", "TUDN", "ViX"],
  431: ["Apple TV", "Fox Sports", "TUDN"],
};

export function getBroadcastChannels(leagueId: number): string[] {
  return BROADCAST_CHANNELS[leagueId] || ["TyC Sports", "ESPN", "Fox Sports"];
}

/* ─── Pelota Libre league name → SUPPORTED_LEAGUES mapping ─── */

const PL_LEAGUE_MAP: Record<string, number> = {
  "liga profesional": 128,
  "liga profesional argentina": 128,
  "copa de la liga": 1032,
  "copa de la liga profesional": 1032,
  "copa argentina": 130,
  "liga de primera": 265,
  "liga de primera chile": 265,
  "primera division chile": 265,
  "chilean primera division": 265,
  "campeonato nacional": 265,
  "copa chile": 267,
  "liga betplay": 239,
  "betplay": 239,
  "categoria primera a": 239,
  "primera a": 239,
  "primera a colombiana": 239,
  "liga colombiana": 239,
  "colombian primera": 239,
  "colombian primera division": 239,
  "colombia primera division": 239,
  "brasileirão serie a": 71,
  "brasileirao serie a": 71,
  "brasileirão": 71,
  "copa do brasil": 73,
  "liga 1": 281,
  "liga 1 peru": 281,
  "liga 1 peruana": 281,
  "liga peruana": 281,
  "copa perú": 503,
  "copa peru": 503,
  "copa paraguay": 501,
  "liga auf uruguaya": 268,
  "liga uruguaya": 268,
  "copa uruguay": 930,
  "copa libertadores": 13,
  "copa conmebol libertadores": 13,
  "libertadores": 13,
  "copa sudamericana": 11,
  "copa conmebol sudamericana": 11,
  "sudamericana": 11,
  "champions league": 2,
  "uefa champions league": 2,
  "europa league": 3,
  "uefa europa league": 3,
  "la liga": 140,
  "laliga": 140,
  "laliga ea sports": 140,
  "premier league": 39,
  "premier": 39,
  "bundesliga": 78,
  "3. liga": 80,
  "3 liga": 80,
  "serie a": 135,
  "serie a italia": 135,
  "copa italia": 137,
  "mls": 332,
  "major league soccer": 332,
  "major league": 332,
  "liga mx": 235,
  "concacaf champions cup": 5,
  "concacaf": 5,
  "leagues cup": 431,
};

const PL_EXCLUDED_LEAGUES = [
  "serie b",
  "ekstraklasa",
  "eredivisie",
  "super lig",
  "ligue 1",
  "primeira liga",
  "liga pro",
  "liga de ecuador",
  "liga ecuatoriana",
  "liga mx femenil",
  "liga de expansión mx",
  "liga de expansion mx",
  "división profesional",
  "division profesional",
];

const ECUADOR_SERIE_A_TEAMS = [
  "ldu quito", "barcelona sc", "emelec", "el nacional", "independiente del valle",
  "universidad católica", "aucas", "delfín", "mushuc runa", "deportivo cuenca",
  "guayaquil city", "libertad", "gualaceo", "orense", "tecnico universitario",
  "macará", "cumbayá", "imbabura", "leones del norte", "rc altoríz",
  "cuniburo", "vinotinto", "anta", "22 de julio", "politécnica",
];

const TEAM_DISPLAY_NAMES: Record<string, string> = {
  "brighton & hove albion": "Brighton",
  "brighton & hove albion fc": "Brighton",
  "manchester united": "Man Utd",
  "manchester city": "Man City",
  "newcastle united": "Newcastle",
  "west ham united": "West Ham",
  "leicester city": "Leicester",
  "aston villa": "Aston Villa",
  "wolverhampton wanderers": "Wolves",
  "nottingham forest": "Nott'm Forest",
  "tottenham hotspur": "Tottenham",
  "sheffield united": "Sheffield Utd",
  "real betis balompié": "Real Betis",
  "real sociedad de fútbol": "Real Sociedad",
  "atlético de madrid": "Atlético Madrid",
  "rcd mallorca": "Mallorca",
  "real valladolid cf": "Valladolid",
  "deportivo alavés": "Alavés",
  "celta de vigo": "Celta Vigo",
  "getafe cf": "Getafe",
  "orca del norte": "Leones del Norte",
  "guayaquil city fc": "Guayaquil City",
  "inter milano": "Inter Milan",
  "inter de milán": "Inter Milan",
  "inter de milan": "Inter Milan",
  "internazionale milano": "Inter Milan",
  "internazionale": "Inter Milan",
  "fc internazionale": "Inter Milan",
  "oud-heverlee leuven": "OH Leuven",
  "oud heverlee leuven": "OH Leuven",
};

export function shortenTeamName(name: string): string {
  return TEAM_DISPLAY_NAMES[name.toLowerCase()] ?? name;
}

export function matchPlLeague(plLeagueName: string, homeTeam?: string, awayTeam?: string): LeagueConfig | null {
  const normalized = plLeagueName.toLowerCase().trim();

  for (const excluded of PL_EXCLUDED_LEAGUES) {
    if (normalized === excluded) return null;
  }

  const leagueId = PL_LEAGUE_MAP[normalized];
  if (leagueId) {
    if (leagueId === 135 && (homeTeam || awayTeam)) {
      const combined = `${homeTeam ?? ""} ${awayTeam ?? ""}`.toLowerCase();
      if (ECUADOR_SERIE_A_TEAMS.some((t) => combined.includes(t))) return null;
    }
    return SUPPORTED_LEAGUES.find((l) => l.id === leagueId) ?? null;
  }
  for (const [key, id] of Object.entries(PL_LEAGUE_MAP)) {
    if (key.length > 3 && (normalized.includes(key) || key.includes(normalized))) {
      if (id === 135 && (homeTeam || awayTeam)) {
        const combined = `${homeTeam ?? ""} ${awayTeam ?? ""}`.toLowerCase();
        if (ECUADOR_SERIE_A_TEAMS.some((t) => combined.includes(t))) return null;
      }
      return SUPPORTED_LEAGUES.find((l) => l.id === id) ?? null;
    }
  }
  return null;
}

export const PROMIEDOS_ALIASES: Record<string, string> = {
  "america": "clubamerica",
  "argentinos": "argentinosjuniors",
  "athleticbilbao": "athleticclub",
  "athleticopr": "athleticoparanaense",
  "atleticopr": "athleticoparanaense",
  "banfield": "banfield",
  "bayern": "bayernmunich",
  "bayernmunchen": "bayernmunich",
  "belgrano": "belgrano",
  "boca": "bocajuniors",
  "borussiamgladbach": "borussiamonchengladbach",
  "bvb": "borussiadortmund",
  "central": "rosariocentral",
  "cerroporteno": "cerroporteno",
  "chivas": "chivasdeguadalajara",
  "clubleon": "leon",
  "defensa": "defensayjusticia",
  "dortmund": "borussiadortmund",
  "estudiantes": "estudiantesdelaplata",
  "gimnasia": "gimnasialaplata",
  "godoy": "godoycruz",
  "godoycruz": "godoycruz",
  "guadalajara": "chivasdeguadalajara",
  "huracan": "huracan",
  "independiente": "independiente",
  "medellin": "independientemedellin",
  "independiente medellin": "independientemedellin",
  "dim": "independientemedellin",
  "inter": "intermilan",
  "inter milano": "intermilan",
  "inter de milan": "intermilan",
  "internazionale": "intermilan",
  "lanus": "lanus",
  "libertad": "libertad",
  "mancity": "manchestercity",
  "manutd": "manchesterunited",
  "nacional": "nacional",
  "newcastle": "newcastleunited",
  "newells": "newellsoldboys",
  "nuevells": "newellsoldboys",
  "olimpia": "olimpia",
  "penarol": "penarol",
  "platense": "platense",
  "porto": "fcporto",
  "psv": "psveindhoven",
  "queretaro": "queretarofc",
  "racing": "racingclub",
  "rayados": "monterrey",
  "river": "riverplate",
  "rosariocentral": "rosariocentral",
  "sanlorenzo": "sanlorenzo",
  "sanluis": "atleticosanluis",
  "spurs": "tottenham",
  "talleres": "talleresdecordoba",
  "tigre": "tigre",
  "tigres": "uanltigres",
  "tigresuanl": "uanltigres",
  "tijuana": "clubtijuana",
  "tottenhamhotspur": "tottenham",
  "unam": "pumas",
  "velez": "velezsarsfield",
  "wolves": "leedsunited",
  "xolos": "clubtijuana",
};


export const PROMIEDOS_BADGES: Record<string, string> = {
  "instituto": "https://api.promiedos.com.ar/images/team/hchc/3",
  "defensayjusticia": "https://api.promiedos.com.ar/images/team/hcbh/3",
  "gimnasiademendoza": "https://api.promiedos.com.ar/images/team/bbjbf/3",
  "velezsarsfield": "https://api.promiedos.com.ar/images/team/ihc/3",
  "independiente": "https://api.promiedos.com.ar/images/team/ihe/3",
  "bocajuniors": "https://api.promiedos.com.ar/images/team/igg/3",
  "lanus": "https://api.promiedos.com.ar/images/team/igj/3",
  "newellsoldboys": "https://api.promiedos.com.ar/images/team/ihh/3",
  "uniondesantafe": "https://api.promiedos.com.ar/images/team/hcag/3",
  "sanlorenzo": "https://api.promiedos.com.ar/images/team/igf/3",
  "estudiantesdelaplata": "https://api.promiedos.com.ar/images/team/igh/3",
  "deportivoriestra": "https://api.promiedos.com.ar/images/team/bbjea/3",
  "platense": "https://api.promiedos.com.ar/images/team/hcah/3",
  "talleresdecordoba": "https://api.promiedos.com.ar/images/team/jche/3",
  "centralcordobasde": "https://api.promiedos.com.ar/images/team/beafh/3",
  "argentinosjuniors": "https://api.promiedos.com.ar/images/team/ihb/3",
  "gimnasialaplata": "https://api.promiedos.com.ar/images/team/iia/3",
  "huracan": "https://api.promiedos.com.ar/images/team/iie/3",
  "sarmientojunin": "https://api.promiedos.com.ar/images/team/hbbh/3",
  "rosariocentral": "https://api.promiedos.com.ar/images/team/ihf/3",
  "independienterivadavia": "https://api.promiedos.com.ar/images/team/hcch/3",
  "belgrano": "https://api.promiedos.com.ar/images/team/fhid/3",
  "atleticotucuman": "https://api.promiedos.com.ar/images/team/gbfc/3",
  "riverplate": "https://api.promiedos.com.ar/images/team/igi/3",
  "tigre": "https://api.promiedos.com.ar/images/team/iid/3",
  "barracascentral": "https://api.promiedos.com.ar/images/team/jafb/3",
  "banfield": "https://api.promiedos.com.ar/images/team/ihi/3",
  "racingclub": "https://api.promiedos.com.ar/images/team/ihg/3",
  "estudiantesrc": "https://api.promiedos.com.ar/images/team/bheaf/3",
  "aldosivi": "https://api.promiedos.com.ar/images/team/hccd/3",
  "godoycruz": "https://api.promiedos.com.ar/images/team/ihd/3",
  "flamengo": "https://api.promiedos.com.ar/images/team/bcbf/3",
  "palmeiras": "https://api.promiedos.com.ar/images/team/bccc/3",
  "athleticoparanaense": "https://api.promiedos.com.ar/images/team/bcba/3",
  "bahia": "https://api.promiedos.com.ar/images/team/bhgh/3",
  "fluminense": "https://api.promiedos.com.ar/images/team/bcbg/3",
  "cruzeiro": "https://api.promiedos.com.ar/images/team/bcbd/3",
  "atleticomineiro": "https://api.promiedos.com.ar/images/team/bcaj/3",
  "santos": "https://api.promiedos.com.ar/images/team/bcce/3",
  "coritiba": "https://api.promiedos.com.ar/images/team/bcbc/3",
  "bragantino": "https://api.promiedos.com.ar/images/team/bchd/3",
  "saopaulo": "https://api.promiedos.com.ar/images/team/bccf/3",
  "botafogo": "https://api.promiedos.com.ar/images/team/bcbb/3",
  "vitoria": "https://api.promiedos.com.ar/images/team/bcci/3",
  "corinthians": "https://api.promiedos.com.ar/images/team/bcgh/3",
  "mirassol": "https://api.promiedos.com.ar/images/team/bcgj/3",
  "vascodagama": "https://api.promiedos.com.ar/images/team/bcch/3",
  "gremio": "https://api.promiedos.com.ar/images/team/bcbi/3",
  "internacional": "https://api.promiedos.com.ar/images/team/bcbj/3",
  "remo": "https://api.promiedos.com.ar/images/team/hdid/3",
  "chapecoense": "https://api.promiedos.com.ar/images/team/hdih/3",
  "colocolo": "https://api.promiedos.com.ar/images/team/bcdj/3",
  "universidadcatolica": "https://api.promiedos.com.ar/images/team/bcef/3",
  "universidaddechile": "https://api.promiedos.com.ar/images/team/ifeb/3",
  "everton": "https://api.promiedos.com.ar/images/team/bah/3",
  "palestino": "https://api.promiedos.com.ar/images/team/bcdi/3",
  "deporteslimache": "https://api.promiedos.com.ar/images/team/fbjie/3",
  "nublense": "https://api.promiedos.com.ar/images/team/bcee/3",
  "deportesconcepcion": "https://api.promiedos.com.ar/images/team/igcj/3",
  "deporteslaserena": "https://api.promiedos.com.ar/images/team/bcdh/3",
  "coquimbounido": "https://api.promiedos.com.ar/images/team/igcf/3",
  "audaxitaliano": "https://api.promiedos.com.ar/images/team/bccj/3",
  "huachipato": "https://api.promiedos.com.ar/images/team/bcdc/3",
  "ohiggins": "https://api.promiedos.com.ar/images/team/bcde/3",
  "deportescobresal": "https://api.promiedos.com.ar/images/team/bcdb/3",
  "udeconcepcion": "https://api.promiedos.com.ar/images/team/bceh/3",
  "ulacalera": "https://api.promiedos.com.ar/images/team/ieaj/3",
  "libertad": "https://api.promiedos.com.ar/images/team/bcig/3",
  "clubnacional": "https://api.promiedos.com.ar/images/team/bcia/3",
  "2demayo": "https://api.promiedos.com.ar/images/team/begec/3",
  "olimpia": "https://api.promiedos.com.ar/images/team/ifei/3",
  "sportivotrinidense": "https://api.promiedos.com.ar/images/team/begea/3",
  "clubguarani": "https://api.promiedos.com.ar/images/team/hhdj/3",
  "sportivoameliano": "https://api.promiedos.com.ar/images/team/fgfii/3",
  "cerroporteno": "https://api.promiedos.com.ar/images/team/bcje/3",
  "sportivoluqueno": "https://api.promiedos.com.ar/images/team/ihhi/3",
  "rubionu": "https://api.promiedos.com.ar/images/team/ihhe/3",
  "recoletafc": "https://api.promiedos.com.ar/images/team/fdcaj/3",
  "cssanlorenzo": "https://api.promiedos.com.ar/images/team/begde/3",
  "montevideocitytorque": "https://api.promiedos.com.ar/images/team/bcghf/3",
  "liverpoolfc": "https://api.promiedos.com.ar/images/team/idfi/3",
  "cerro": "https://api.promiedos.com.ar/images/team/hehh/3",
  "penarol": "https://api.promiedos.com.ar/images/team/hhgg/3",
  "juventud": "https://api.promiedos.com.ar/images/team/babjc/3",
  "racingclubmontevideo": "https://api.promiedos.com.ar/images/team/haih/3",
  "deportivomaldonado": "https://api.promiedos.com.ar/images/team/beagc/3",
  "montevideowanderers": "https://api.promiedos.com.ar/images/team/igbe/3",
  "progreso": "https://api.promiedos.com.ar/images/team/babjb/3",
  "bostonriver": "https://api.promiedos.com.ar/images/team/bcghd/3",
  "nacional": "https://api.promiedos.com.ar/images/team/hehi/3",
  "cerrolargo": "https://api.promiedos.com.ar/images/team/igbi/3",
  "centralespanol": "https://api.promiedos.com.ar/images/team/babjd/3",
  "defensorsporting": "https://api.promiedos.com.ar/images/team/hgdj/3",
  "danubiofc": "https://api.promiedos.com.ar/images/team/igbb/3",
  "albion": "https://api.promiedos.com.ar/images/team/fbfcc/3",
  "independientemedellin": "https://api.promiedos.com.ar/images/team/iged/3",
  "puertomontt": "https://r2.thesportsdb.com/images/media/team/badge/k1wdah1677471408.png",
  "deportespuertomontt": "https://r2.thesportsdb.com/images/media/team/badge/k1wdah1677471408.png",
  "ohleuven": "https://r2.thesportsdb.com/images/media/team/badge/3ra01v1783527582.png",
  "oudheverleeleuven": "https://r2.thesportsdb.com/images/media/team/badge/3ra01v1783527582.png",
  "ohl": "https://r2.thesportsdb.com/images/media/team/badge/3ra01v1783527582.png",
  "leuven": "https://r2.thesportsdb.com/images/media/team/badge/3ra01v1783527582.png",
  "cuscofc": "https://api.promiedos.com.ar/images/team/jcjb/3",
  "deportestolima": "https://api.promiedos.com.ar/images/team/hgdf/3",
  "universitario": "https://api.promiedos.com.ar/images/team/hbgj/3",
  "bolivar": "https://api.promiedos.com.ar/images/team/hchi/3",
  "deportivolaguaira": "https://api.promiedos.com.ar/images/team/bdbeg/3",
  "barcelonasc": "https://api.promiedos.com.ar/images/team/jbda/3",
  "independientesantafe": "https://api.promiedos.com.ar/images/team/hgee/3",
  "sportingcristal": "https://api.promiedos.com.ar/images/team/ieca/3",
  "juniorfc": "https://api.promiedos.com.ar/images/team/hcae/3",
  "ligadequito": "https://api.promiedos.com.ar/images/team/bcic/3",
  "alwaysready": "https://api.promiedos.com.ar/images/team/efidc/3",
  "independientedelvalle": "https://api.promiedos.com.ar/images/team/jbec/3",
  "universidadcentralfc": "https://api.promiedos.com.ar/images/team/bdidi/3",
  "macara": "https://api.promiedos.com.ar/images/team/jbea/3",
  "americadecali": "https://api.promiedos.com.ar/images/team/igef/3",
  "alianzaatletico": "https://api.promiedos.com.ar/images/team/iebi/3",
  "cienciano": "https://api.promiedos.com.ar/images/team/iebc/3",
  "puertocabello": "https://api.promiedos.com.ar/images/team/cfffj/3",
  "millonarios": "https://api.promiedos.com.ar/images/team/igdh/3",
  "deportivocuenca": "https://api.promiedos.com.ar/images/team/hcib/3",
  "caracasfc": "https://api.promiedos.com.ar/images/team/igig/3",
  "independientepetrolero": "https://api.promiedos.com.ar/images/team/fdjie/3",
  "carabobofc": "https://api.promiedos.com.ar/images/team/igie/3",
  "blooming": "https://api.promiedos.com.ar/images/team/hdac/3",
  "psg": "https://api.promiedos.com.ar/images/team/eia/3",
  "bayernmunich": "https://api.promiedos.com.ar/images/team/ddb/3",
  "fcbarcelona": "https://api.promiedos.com.ar/images/team/bdc/3",
  "manchesterunited": "https://api.promiedos.com.ar/images/team/baf/3",
  "como": "https://api.promiedos.com.ar/images/team/gbbh/3",
  "sportingcp": "https://api.promiedos.com.ar/images/team/ija/3",
  "stuttgart": "https://api.promiedos.com.ar/images/team/ddi/3",
  "manchestercity": "https://api.promiedos.com.ar/images/team/bba/3",
  "astonvilla": "https://api.promiedos.com.ar/images/team/baj/3",
  "lens": "https://api.promiedos.com.ar/images/team/eib/3",
  "realbetis": "https://api.promiedos.com.ar/images/team/beg/3",
  "borussiadortmund": "https://api.promiedos.com.ar/images/team/deb/3",
  "liverpool": "https://api.promiedos.com.ar/images/team/bai/3",
  "realmadrid": "https://api.promiedos.com.ar/images/team/bdb/3",
  "arsenal": "https://api.promiedos.com.ar/images/team/bae/3",
  "aekatenas": "https://api.promiedos.com.ar/images/team/bace/3",
  "asroma": "https://api.promiedos.com.ar/images/team/ccf/3",
  "shakhtardonetsk": "https://api.promiedos.com.ar/images/team/bjff/3",
  "fenerbahce": "https://api.promiedos.com.ar/images/team/jeg/3",
  "psveindhoven": "https://api.promiedos.com.ar/images/team/hcf/3",
  "villarrealcf": "https://api.promiedos.com.ar/images/team/bdd/3",
  "brujas": "https://api.promiedos.com.ar/images/team/bbgj/3",
  "lille": "https://api.promiedos.com.ar/images/team/ehi/3",
  "slaviapraga": "https://api.promiedos.com.ar/images/team/bhij/3",
  "atleticodemadrid": "https://api.promiedos.com.ar/images/team/bde/3",
  "intermilan": "https://api.promiedos.com.ar/images/team/cce/3",
  "lasklinz": "https://api.promiedos.com.ar/images/team/bhed/3",
  "napoli": "https://api.promiedos.com.ar/images/team/cde/3",
  "galatasaray": "https://api.promiedos.com.ar/images/team/jef/3",
  "viking": "https://api.promiedos.com.ar/images/team/bjia/3",
  "fcporto": "https://api.promiedos.com.ar/images/team/iih/3",
  "rbleipzig": "https://api.promiedos.com.ar/images/team/hbhb/3",
  "feyenoord": "https://api.promiedos.com.ar/images/team/gjb/3",
  "sabah": "https://api.promiedos.com.ar/images/team/facab/3",
  "slovanbratislava": "https://api.promiedos.com.ar/images/team/cbbc/3",
  "bodoglimt": "https://api.promiedos.com.ar/images/team/bjhi/3",
  "juventus": "https://api.promiedos.com.ar/images/team/ccg/3",
  "crystalpalace": "https://api.promiedos.com.ar/images/team/ba/3",
  "spartapraga": "https://api.promiedos.com.ar/images/team/bhii/3",
  "besiktas": "https://api.promiedos.com.ar/images/team/jeh/3",
  "unionstgilloise": "https://api.promiedos.com.ar/images/team/bcae/3",
  "ferencvaros": "https://api.promiedos.com.ar/images/team/gaca/3",
  "benfica": "https://api.promiedos.com.ar/images/team/iii/3",
  "bayerleverkusen": "https://api.promiedos.com.ar/images/team/ddd/3",
  "oficrete": "https://api.promiedos.com.ar/images/team/badc/3",
  "bournemouth": "https://api.promiedos.com.ar/images/team/fa/3",
  "lyon": "https://api.promiedos.com.ar/images/team/egf/3",
  "torreense": "https://api.promiedos.com.ar/images/team/jcb/3",
  "olympiacos": "https://api.promiedos.com.ar/images/team/bacd/3",
  "redbullsalzburgo": "https://api.promiedos.com.ar/images/team/bhdj/3",
  "omonia": "https://api.promiedos.com.ar/images/team/ccgc/3",
  "sunderland": "https://api.promiedos.com.ar/images/team/bbh/3",
  "dinamozagreb": "https://api.promiedos.com.ar/images/team/ccef/3",
  "hapoelbeersheva": "https://api.promiedos.com.ar/images/team/fhj/3",
  "rennes": "https://api.promiedos.com.ar/images/team/ehh/3",
  "sturmgraz": "https://api.promiedos.com.ar/images/team/bheb/3",
  "jagiellonia": "https://api.promiedos.com.ar/images/team/ccca/3",
  "anderlecht": "https://api.promiedos.com.ar/images/team/bbhd/3",
  "lillestrom": "https://api.promiedos.com.ar/images/team/bjif/3",
  "realsociedad": "https://api.promiedos.com.ar/images/team/bfe/3",
  "azalkmaar": "https://api.promiedos.com.ar/images/team/gjj/3",
  "celtadevigo": "https://api.promiedos.com.ar/images/team/bfi/3",
  "levskisofia": "https://api.promiedos.com.ar/images/team/cchh/3",
  "celtic": "https://api.promiedos.com.ar/images/team/hfe/3",
  "acmilan": "https://api.promiedos.com.ar/images/team/cch/3",
  "nkcelje": "https://api.promiedos.com.ar/images/team/cdef/3",
  "hoffenheim": "https://api.promiedos.com.ar/images/team/dfb/3",
  "olympiquemarsella": "https://api.promiedos.com.ar/images/team/egj/3",
  "fcararatarmenia": "https://api.promiedos.com.ar/images/team/eiihj/3",
  "viktoriaplzen": "https://api.promiedos.com.ar/images/team/bhjg/3",
  "lechpoznan": "https://api.promiedos.com.ar/images/team/ccbb/3",
  "necnijmegen": "https://api.promiedos.com.ar/images/team/haa/3",
  "sevillafc": "https://api.promiedos.com.ar/images/team/bdf/3",
  "alaves": "https://api.promiedos.com.ar/images/team/bgi/3",
  "rcdeportivo": "https://api.promiedos.com.ar/images/team/bei/3",
  "athleticclub": "https://api.promiedos.com.ar/images/team/bee/3",
  "getafecf": "https://api.promiedos.com.ar/images/team/bea/3",
  "rayovallecano": "https://api.promiedos.com.ar/images/team/bhe/3",
  "osasuna": "https://api.promiedos.com.ar/images/team/bed/3",
  "rcdespanyol": "https://api.promiedos.com.ar/images/team/bdg/3",
  "racingdesantander": "https://api.promiedos.com.ar/images/team/bdh/3",
  "levanteud": "https://api.promiedos.com.ar/images/team/bfa/3",
  "elchecf": "https://api.promiedos.com.ar/images/team/bfg/3",
  "valenciacf": "https://api.promiedos.com.ar/images/team/bdj/3",
  "malagacf": "https://api.promiedos.com.ar/images/team/bfc/3",
  "brighton": "https://api.promiedos.com.ar/images/team/di/3",
  "brentford": "https://api.promiedos.com.ar/images/team/gd/3",
  "leedsunited": "https://api.promiedos.com.ar/images/team/dg/3",
  "hullcity": "https://api.promiedos.com.ar/images/team/bb/3",
  "newcastleunited": "https://api.promiedos.com.ar/images/team/bbg/3",
  "chelsea": "https://api.promiedos.com.ar/images/team/bag/3",
  "ipswich": "https://api.promiedos.com.ar/images/team/j/3",
  "nottinghamforest": "https://api.promiedos.com.ar/images/team/cj/3",
  "coventry": "https://api.promiedos.com.ar/images/team/ce/3",
  "fulham": "https://api.promiedos.com.ar/images/team/bca/3",
  "tottenham": "https://api.promiedos.com.ar/images/team/bbe/3",
  "friburgo": "https://api.promiedos.com.ar/images/team/dfe/3",
  "fcaugsburg": "https://api.promiedos.com.ar/images/team/dfi/3",
  "mainz05": "https://api.promiedos.com.ar/images/team/dfc/3",
  "sv07elversberg": "https://api.promiedos.com.ar/images/team/ebi/3",
  "werderbremen": "https://api.promiedos.com.ar/images/team/ddc/3",
  "eintrachtfrankfurt": "https://api.promiedos.com.ar/images/team/ddh/3",
  "schalke04": "https://api.promiedos.com.ar/images/team/ddf/3",
  "1fckoln": "https://api.promiedos.com.ar/images/team/dfa/3",
  "hamburgosv": "https://api.promiedos.com.ar/images/team/dde/3",
  "scpaderborn07": "https://api.promiedos.com.ar/images/team/dgg/3",
  "unionberlin": "https://api.promiedos.com.ar/images/team/djc/3",
  "borussiamonchengladbach": "https://api.promiedos.com.ar/images/team/dej/3",
  "lazio": "https://api.promiedos.com.ar/images/team/cdg/3",
  "cagliari": "https://api.promiedos.com.ar/images/team/ced/3",
  "frosinone": "https://api.promiedos.com.ar/images/team/cfe/3",
  "sassuolo": "https://api.promiedos.com.ar/images/team/cgg/3",
  "atalanta": "https://api.promiedos.com.ar/images/team/cdc/3",
  "lecce": "https://api.promiedos.com.ar/images/team/ceg/3",
  "parma": "https://api.promiedos.com.ar/images/team/ceb/3",
  "torino": "https://api.promiedos.com.ar/images/team/cdf/3",
  "udinese": "https://api.promiedos.com.ar/images/team/ccj/3",
  "monza": "https://api.promiedos.com.ar/images/team/cjd/3",
  "fiorentina": "https://api.promiedos.com.ar/images/team/cci/3",
  "bologna": "https://api.promiedos.com.ar/images/team/cef/3",
  "genoa": "https://api.promiedos.com.ar/images/team/cdb/3",
  "venezia": "https://api.promiedos.com.ar/images/team/dai/3",
  "toluca": "https://api.promiedos.com.ar/images/team/cahi/3",
  "chivasdeguadalajara": "https://api.promiedos.com.ar/images/team/bcfj/3",
  "clubamerica": "https://api.promiedos.com.ar/images/team/bcff/3",
  "cruzazul": "https://api.promiedos.com.ar/images/team/bcgb/3",
  "puebla": "https://api.promiedos.com.ar/images/team/bcfc/3",
  "atlas": "https://api.promiedos.com.ar/images/team/bcfi/3",
  "monterrey": "https://api.promiedos.com.ar/images/team/bcfh/3",
  "queretarofc": "https://api.promiedos.com.ar/images/team/fjje/3",
  "leon": "https://api.promiedos.com.ar/images/team/jddj/3",
  "clubtijuana": "https://api.promiedos.com.ar/images/team/ifai/3",
  "pumas": "https://api.promiedos.com.ar/images/team/bcej/3",
  "pachuca": "https://api.promiedos.com.ar/images/team/bcfa/3",
  "atleticosanluis": "https://api.promiedos.com.ar/images/team/bcga/3",
  "atlante": "https://api.promiedos.com.ar/images/team/caih/3",
  "necaxa": "https://api.promiedos.com.ar/images/team/bcgd/3",
  "uanltigres": "https://api.promiedos.com.ar/images/team/bcge/3",
  "santoslaguna": "https://api.promiedos.com.ar/images/team/bcfe/3",
  "juarez": "https://api.promiedos.com.ar/images/team/cfbej/3",
};
